#ALTER TABLE Celebrity ALTER COLUMN bio DROP NOT NULL;
#ALTER TABLE Celebrity ALTER COLUMN bio SET NOT NULL;

ALTER TABLE Address ALTER COLUMN addressline2 DROP NOT NULL;

ALTER TABLE Celebrity ALTER COLUMN publicname SET NOT NULL;
ALTER TABLE Celebrity ALTER COLUMN urlslug SET NOT NULL;

