package models.checkout

import org.joda.money.{CurrencyUnit, Money}
import models.enums._
import org.squeryl.KeyedEntity
import org.squeryl.PrimitiveTypeMode._
import java.sql.Timestamp
import services.{AppConfig, Time}
import services.db._
import models.{Customer, HasCreatedUpdated, SavesCreatedUpdated}
import com.google.inject.Inject
import services.payment.Charge


// NOTE(SER-499): CashTransaction sets convention that payments to us are positive

/**
 * TODO: Refunds
 * -implement a product refund type and item for the purpose of canceling out its targetted
 *  item or type in the calculation of new totals (e.g. #1 above)
 *   -refunding tax could be separate or combined into product's refund amount
 * -implement a refund charge type to represent the credit made back to the customer
 */

// TODO(SER-499): most of this should not remain in pull request, just here for keeping track of noise generated by design
package object checkout {
  /** For _domainEntityId if domain object doesn't get persisted; ex: Tax */
  val UnusedDomainEntity: Long = -1

  /** For id's of line items and line item types that don't get persisted; ex: Subtotal */
  val Unpersisted: Long = -2

  val UnsavedEntity = 0

  type LineItems = Seq[LineItem[_]]
  type LineItemTypes = Seq[LineItemType[_]]
}

import checkout._



// TODO(SER-499): look into why store isn't usually combined into services (modeling concern probs)
//
// Services
//
class CheckoutServices @Inject() (
  schema: Schema,
  lineItemStore: LineItemStore
) extends InsertsAndUpdatesAsEntity[Checkout, CheckoutEntity]
  with SavesCreatedUpdated[CheckoutEntity]
{
  override protected def table = schema.checkouts

  override def modelWithNewEntity(checkout: Checkout, entity: CheckoutEntity) = checkout.copy(entity)

  override def withCreatedUpdated(toUpdate: CheckoutEntity, created: Timestamp, updated: Timestamp) = {
    toUpdate.copy(created=created, updated=updated)
  }

  def findById(id: Long): Option[Checkout] = table.lookup(id).map { entity =>
    Checkout(entity, lineItemStore.getItemsByCheckoutId(entity.id))
  }

  def getCheckoutsByCustomerId(id: Long): Seq[Checkout] = {
    val checkouts = for (
      checkoutEntity <- table.where(entity => entity.customerId === id);
      checkout <- findById(checkoutEntity.id)
    ) yield checkout

    checkouts.toSeq
  }
}


//
// Entity
//
case class CheckoutEntity(
  id: Long = 0,
  customerId: Long = 0,
  created: Timestamp = Time.defaultTimestamp,
  updated: Timestamp = Time.defaultTimestamp
) extends KeyedCaseClass[Long] with HasCreatedUpdated {
  override def unapplied = CheckoutEntity.unapply(this)
}



//
// Model
//
case class Checkout (
  _entity: CheckoutEntity,
  _typesOrItems: Either[LineItemTypes, LineItems],
  _additionalTypes: LineItemTypes = Nil,
  services: CheckoutServices = AppConfig.instance[CheckoutServices]
) extends HasEntity[CheckoutEntity, Long] with KeyedCaseClass[Long]
  with CanInsertAndUpdateAsThroughServices[Checkout, CheckoutEntity]
{

  // uses LineItems and LineItemTypes
  lazy val lineItems: LineItems =  _typesOrItems match {
    case Right(items: LineItems) => resolveTypes(_additionalTypes, items)
    case Left(types: LineItemTypes) => resolveTypes(types)
  }

  lazy val lineItemTypes: LineItemTypes = _typesOrItems match {
    case Left(types: LineItemTypes) => types
    case Right(items: LineItems) => _additionalTypes ++ items.map(_.itemType)
  }



  /**
   * To be used for adding any line item types (products, discounts, refunds, etc)
   * @param additionalTypes -- to be added to this checkout
   * @return If transacted, checkout with additionalTypes in _additionalTypes; otherwise, checkout
   *         with _additionalTypes added to lineItemTypes.
   */
  def withAdditionalTypes(additionalTypes: LineItemTypes) = {
    if (id > 0) {
      this.copy(_additionalTypes = additionalTypes ++ _additionalTypes)
    } else {
      this.copy(_typesOrItems = Left(additionalTypes ++ lineItemTypes))
    }
  }

  /**
   * Persists this checkout, its types, and its items
   * @return PersistedCheckout of the transacted checkout
   */
  def transact(): Checkout = {
    // TODO(SER-499): take charge information, make charge

    // TODO(SER-499): require payment/sum of [products, fees, taxes]/total and charges to be zero.
    // TODO(SER-499): make transact take checkout context
    if (id > 0) {
      updateTransaction()

    } else {

      // Completely untransacted
      val savedCheckout = this.insert()
      val savedItems = savedCheckout.lineItems.map( item => item.transact(savedCheckout.id) )

      this.copy(savedCheckout._entity, Right(savedItems))
    }
  }

  /**
   * Updates an existing checkout and its contents.
   * - intend to use original tax rates at the point of purchase for now
   *   * if updates happen after tax changes, calculated taxes will not match taxes of newly made purchase
   * - should refund taxes
   * - TODO: should not refund fees (e.g. shipping)
   *
   * @return Updated checkout
   */
  protected def updateTransaction(): Checkout = {
    // TODO(SER-499): clean this whole bessy up
    if (_additionalTypes.isEmpty) {
      this // NOTE(SER-499): doesn't touch updated timestamp, is that okay?

    } else {
      import LineItemNature._

      def grossToNet(gross: LineItems, old: LineItems) = gross.flatMap { newItem =>
        val oldAmount = old.find(_.itemType == newItem.itemType).map(_.amount).getOrElse(Money.zero(CurrencyUnit.USD))

        if (oldAmount isGreaterThan newItem.amount) None
        else Some(newItem.withAmount(newItem.amount minus oldAmount))
      }

      def replaceItems(oldItems: LineItems, replacementItems: LineItems) =
        replacementItems.foldLeft(oldItems){ (itemsAcc, nextReplacementItem) =>
          itemsAcc.updated(
            itemsAcc.indexWhere(item => item.itemType == nextReplacementItem.itemType),
            nextReplacementItem
          )
        }

      /**
       * Need to:
       * 1. Get the new taxes, fees, total as the difference between what a fresh checkout with all
       *    of this carts line item types produces and the ones that already exist in this checkout
       * 2. Collect and transact items from _additionalTypes and the new taxes and fees
       * 3. Return checkout with no _additionalTypes, just transacted line items
       *
       * - make sure not to try to get the newly created items (from _additionalTypes) from the
       *   tempCheckout because all its lineItems will appear unpersisted (since they are, technically)
       */

      val oldTaxes = lineItemsOfNature(Tax)
      val oldFees = lineItemsOfNature(Fee)

      /** calculate new fees, taxes, total */
      // Has all tax, fee, & summary types, will apply them to entire checkout
      val tempCheckout = new Checkout(CheckoutEntity(), Left(lineItemTypes))

      val grossNewTaxes = tempCheckout.lineItemsOfNature(Tax)
      val grossNewFees = tempCheckout.lineItemsOfNature(Fee)
      val netNewTaxes = grossToNet(grossNewTaxes, oldTaxes)
      val netNewFees = grossToNet(grossNewFees, oldFees)
      val newItems = netNewTaxes ++ netNewFees ++ lineItems.filter(item => _additionalTypes.contains(item.itemType))


      assert(netNewTaxes.map(item => item.itemType).toSet.size == netNewTaxes.size, "There should be no duplicate taxes.")
      assert(netNewFees.map(item => item.itemType).toSet.size == netNewFees.size, "There should be no duplicate fees.")


      /** transact items from _additionalTypes and new taxes, fees, etc associated with them */
      _typesOrItems match {
        case Right(alreadyTransactedItems: LineItems) =>
          // TODO(SER-499): require sum of amounts is zero
          val newItemsTransacted = newItems.map( item => item.transact(id) )

          val updatedLineItems = newItemsTransacted ++
            replaceItems(alreadyTransactedItems, Seq(tempCheckout.subtotal, tempCheckout.total))

          this.copy(_typesOrItems = Right(updatedLineItems), _additionalTypes = Nil).update()

        case _ => throw new Exception("Cannot update checkout because it has not been inserted yet.")
      }

    }
  }


  //
  // KeyedCaseClass members
  //
  override def id = _entity.id
  override def unapplied = ( _entity, lineItems.map(item => item.unapplied).toSet )


  //
  // utility members
  //
  def subtotal: SubtotalLineItem = lineItemsOfCodeType(CodeType.Subtotal).head
  def total: TotalLineItem = lineItemsOfCodeType(CodeType.Total).head

  def flattenLineItems: LineItems = {
    for (lineItem <- lineItems; flattened <- lineItem.flatten) yield flattened
  }

  def lineItemsOfCodeType[ LIT <: LineItemType[_], LI  <: LineItem[_] ] (codeType: CodeTypeFactory[LIT, LI]): Seq[LI] = {
    for (item <- lineItems if item.codeType == codeType) yield item.asInstanceOf[LI]
  }

  def lineItemsOfNature(nature: LineItemNature) = lineItems.filter(_.nature == nature)

  protected def resolveTypes(types: LineItemTypes, preexistingItems: LineItems = Seq()) = {

    case class ResolutionPass(resolved: LineItems = preexistingItems, unresolved: LineItemTypes) {
      def execute: ResolutionPass = {
        /**
         * Iterates over unresolved in linear time on average (only counting iteration time)
         *
         * @param acc - accumulator of line items, should include previously resolved
         * @param before - item types preceding current type in iteration from list of all types
         * @param curr - current line item type being iterated over
         * @param after - remaining line item types to be iterated over
         * @return - ResolutionPass of resulting resolved items and unresolved types
         */
        def iterate(acc: LineItems = resolved)(
          before: LineItemTypes = Nil,
          curr: LineItemType[_] = unresolved.head,
          after: LineItemTypes = unresolved.tail
        ): ResolutionPass = (after, curr.lineItems(acc, before ++ after)) match {
          case (Nil, Nil) => ResolutionPass(acc, curr +: before)
          case (Nil, res) => ResolutionPass(res ++ acc,  before)
          case (next :: rest, Nil) => iterate(acc)(curr +: before, next, rest)
          case (next :: rest, res) => iterate(res ++ acc)( before, next, rest)
        }

        if (unresolved.isEmpty) this  // no additional to resolve
        else iterate()()              // iterate over unresolved
      }

      override def equals(that: Any) = that match {
        case ResolutionPass(thoseResolved, thoseUnresolved) =>
          (resolved.length, unresolved.length) == (thoseResolved.length, thoseUnresolved.length)
        case _ => false
      }
    }

    def resolve(pass: ResolutionPass): LineItems = {
      pass.execute match {
        case ResolutionPass(allItems, Nil) => allItems
        case unchangedPass if (unchangedPass == pass) =>
          throw new Exception("Failed to resolve line items, circular dependency detected.")
        case intermediatePass => resolve(intermediatePass)
      }
    }

    resolve(ResolutionPass(unresolved = types))
  }
}




object Checkout {
  import checkout._

  // Create
  def apply(types: LineItemTypes, zipcode: String) = {
    val maybeZipcode = if (zipcode.isEmpty) None else Some(zipcode)
    val typesWithTaxesAndSummaries = types ++ taxesAndSummariesByZip(maybeZipcode)

    new Checkout(CheckoutEntity(), Left(typesWithTaxesAndSummaries))
  }

  // Restore
  def apply(entity: CheckoutEntity, items: LineItems) = {
    assert(!items.exists(item => item.checkoutId != entity.id))
    new Checkout(entity, Right(itemsWithSummaries(items)))
  }


  /**
   * Helper for generating taxes and summaries.
   * TODO: add fees, such as shipping, later.
   *
   * @param maybeZipcode - None defaults to no taxes
   * @return Sequence of subtotal, taxes, and total (in that order)
   */
  protected def taxesAndSummariesByZip(maybeZipcode: Option[String]): LineItemTypes = {
    Seq(SubtotalLineItemType) ++
      TaxLineItemType.getTaxesByZip(maybeZipcode.getOrElse(TaxLineItemType.noZipcode)) ++
      Seq(TotalLineItemType)
  }

  protected def itemsWithSummaries(items: LineItems): LineItems = {
    val nonSummaries = items.filter (item => item.nature != LineItemNature.Summary )

    val subtotal = items.find( item => item.codeType == CodeType.Subtotal )
      .getOrElse(SubtotalLineItemType.lineItems(nonSummaries, Seq()).head)

    val total = items.find( item => item.codeType == CodeType.Total )
      .getOrElse(TotalLineItemType.lineItems(nonSummaries, Seq()).head)

    subtotal +: (total +: nonSummaries)
  }
}


