#!/bin/bash
#
# Deploys the application to our hosting...which is currently Cloudbees.
#

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJ_BASE=$SCRIPT_DIR/..

cd $PROJ_BASE

play bees:app:deploy --%live
