#!/bin/bash
#
# Deploys the application to our hosting...which is currently Cloudbees.
#
# $1 - The server to which to deploy. Options:
#        'live' - the publicly-facing egraphs server.
#        'demo' - the demo server, used for hard-wired.
#        'staging' - the staging server.
#


# Parse the deployment target
DEPLOY_TARGET=$1

case "$DEPLOY_TARGET" in
  'live')
    # Check to make super-d-duper sure they want to deploy to live.
    echo ""
    echo "YOU ARE ABOUT TO DEPLOY TO THE PRODUCTION SERVER."
    printf "If this is what you wanted, type \e[00;32mYes\e[00m, press enter, and pray.\n"
    read -e \
         -p ">> " \
         YES_DEPLOY

    if [ "$YES_DEPLOY" != "Yes" ]; then
        echo "Guess you didn't want to deploy to live after all."
        exit 2
    fi

    ;;
  'demo'|'staging')
    # It's always ok to deploy to demo and staging.
	;;
  *)
	# Error us out -- no valid deployment target
    printf "\e[00;31mERROR: '$DEPLOY_TARGET' is not a valid deployment target. Please provide a valid deployment target.\e[00m\n"
    echo ""
    echo "Usage: "
    echo "    tools/deploy [deployment target]"
    echo "Valid deployment targets are 'live', 'demo', and 'staging'. (omit the single quotes)"
    exit 1
	;;  
esac

printf "\e[00;32mDeploying application to target '$DEPLOY_TARGET'.\e[00m\n\n"

# OK everything's groovy...let's do the deploy from the project base folder
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJ_BASE=$SCRIPT_DIR/..

cd $PROJ_BASE

play evolutions:apply --%$DEPLOY_TARGET
play bees:app:deploy --%$DEPLOY_TARGET
